DROP TABLE IF EXISTS `users`, `comments`;

CREATE TABLE `users` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `comments` (
	`id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	`userId` INTEGER UNSIGNED NOT NULL,
	`comment` TEXT NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`userId`) REFERENCES `users`(`id`)
);
